### ISSUE TITLE
哇哦，giegie真不错哦

### ISSUE THREAD

**Issue by LaBiXiaoChen** [LiHaoGo/LiHaoGo.github.io#1]
哇哦，giegie真不错哦哇哦，giegie真不错哦哇哦，giegie真不错哦哇哦，giegie真不错哦哇哦，giegie真不错哦

**Comment by LiHaoGo** [comment]
我直接对你指指点点

**Comment by LaBiXiaoChen** [comment]
牛逼，666，我里宝贝。github使用一个issue不关闭，然后显示给所有人看的方式，然后问题解决就会关闭这个issue，就完成了一个问题的解答。
